# Generated by Django 4.2.19 on 2025-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Booking_Date',
            field=models.DateField(),
        ),
    ]
